
/**
 * {@code FGParserKernel} enhanced with secondary methods, giving capability to
 * parse moves based on movement and button imputs.
 */
public interface FGParser extends FGParserKernel {

    /**
     * generates an attack based on {@code this} given the input {@code button}.
     *
     * @param button
     *            button press to be parsed into an attack
     * @return returns string name of attack generated by movement inputs in
     *         {@code this} and the {@code button}
     * @updates this
     * @requires button is substring of at least one move in {@code this}
     * @ensures generateAttack = highest priority move
     */
    String generateAttack(String button);

    /**
     * Adds a new move to {@code this} with name {@code name} and input
     * {@code input}.
     *
     * @param input
     *            input chain needed to activate move
     * @param name
     *            name of move that will be returned when parsed
     * @updates this
     * @requires {@code input} length >= 1 && is not in {@code this},
     *           {@code name} length >= 1 && is not in {@code this}
     * @ensures this = #this + <input, name>
     */
    void addMove(String input, String name);

    /**
     * Move with given {@code name} dies and doesn't come back (it is deleted
     * without returning the value).
     *
     * @param name
     *            Name of move to be deleted.
     * @updates this
     * @requires {@code this} contians name.
     * @ensures this = #this - <getInput(name), name>
     */
    void deleteMove(String name);

    /**
     * Gets the name of a move with the given input, returns "N/A" if not
     * present.
     *
     * @param input
     *            input of the move to be gotten.
     * @return name of move associated with the given input.
     * @ensures returns associated name, if present
     */
    String getMove(String input);

    /**
     * Gets the input of a move with the given name, returns "N/A" if not
     * present.
     *
     * @param name
     *            name of the move to be gotten.
     * @return The inputs necessary to parse the given name of move.
     * @ensures returns associated inputs, if present
     */
    String getInput(String name);

    /**
     * Deletes all the moves currently saved in the object without deleting the
     * input queue.
     *
     * @clears this.moves
     * @ensures this.moves = {}
     */
    void clearMoves();

}
